version: '3'
services:
  barman:
    image: quay.io/rapyuta/barman:3.5.0
    build:
      context: .
    network_mode: host
    container_name: barman
    hostname: barman
    restart: always
    env_file:
      - barman-variables.env
    volumes:
      - /var/lib/barman/barman:/var/lib/barman
      - /var/lib/barman/logs:/var/log/barman